# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20170223_2213'),
        ('account', '0004_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
    ]
