# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20170219_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=20)),
                ('reservation', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='course.Teacher'),
        ),
    ]
