# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20170220_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre',
            field=models.ManyToManyField(blank=True, to='course.Pre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pro',
            field=models.ManyToManyField(blank=True, to='course.Pro'),
        ),
    ]
