# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20170220_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ta',
            name='reservation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='reservation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
