# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20170220_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='homework',
            field=models.ManyToManyField(blank=True, to='course.Homework'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ta',
            field=models.ManyToManyField(blank=True, to='course.TA'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='course.Teacher'),
        ),
    ]
